version: '3.8'

services:
  db:
    image: postgres:16
    container_name: booking_db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aslan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Booking/Dockerfile
    container_name: booking_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5033:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - images_data:/app/wwwroot/images

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: booking_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  images_data: